upgrade: true
reject:
  - '@babel/core'
  - '@expo/config-plugins'
  - '@expo/config'
  - '@expo/metro-config'
  - '@expo/vector-icons'
  - '@expo/webpack-config'
  - '@react-native-async-storage/async-storage'
  - '@react-native-community/netinfo'
  - '@react-native-firebase/app'
  - '@react-native-firebase/messaging'
  - '@react-native-masked-view/masked-view'
  - '@shopify/flash-list'
  - '@testing-library/jest-native'
  - '@testing-library/react-native'
  - '@types/react-native'
  - '@types/react-test-renderer'
  - '@types/react'
  - axios
  - color
  - expo
  - expo-app-loading
  - expo-application
  - expo-asset
  - expo-auth-session
  - expo-av
  - expo-background-fetch
  - expo-barcode-scanner
  - expo-blur
  - expo-build-properties
  - expo-calendar
  - expo-camera
  - expo-clipboard
  - expo-constants
  - expo-contacts
  - expo-crypto
  - expo-dev-client
  - expo-device
  - expo-error-recovery
  - expo-file-system
  - expo-font
  - expo-haptics
  - expo-image-picker
  - expo-linear-gradient
  - expo-linking
  - expo-localization
  - expo-location
  - expo-navigation-bar
  - expo-network
  - expo-notifications
  - expo-print
  - expo-random
  - expo-screen-capture
  - expo-screen-orientation
  - expo-secure-store
  - expo-sharing
  - expo-splash-screen
  - expo-sqlite
  - expo-status-bar
  - expo-system-ui
  - expo-task-manager
  - expo-updates
  - expo-web-browser
  - jest
  - jest-expo
  - lottie-react-native
  - metro-minify-terser
  - native-base
  - react
  - react-dom
  - react-native
  - react-native-animateable-text
  - react-native-gesture-handler
  - react-native-maps
  - react-native-pager-view
  - react-native-reanimated
  - react-native-safe-area-context
  - react-native-screens
  - react-native-shared-element
  - react-native-svg
  - react-native-view-shot
  - react-native-web
  - react-native-webview
  - react-test-renderer
  - sentry-expo
  - ts-jest
  - typescript
  - use-subscription
  - '@sentry/react-native'
